- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker repository
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Install Docker
  apt:
    update_cache: yes
    name: docker-ce
    state: present

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Ensure Docker starts on boot
  systemd:
    name: docker
    enabled: yes

- name: Ensure user is added to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
